# font handling
# Main font: pure JetBrains Mono (must be installed from JetBrains)
# Main font is the Nerd Font patched version
font_family      "JetBrainsMono Nerd Font"

# Bold/italic variants (optional, can stay auto)
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11


mouse_hide_wait                 2.0
cursor_shape                    beam
cursor                          #fdfd96
cursor_beam_thickness           3
url_color                       #fdfd96
url_style                       curly
confirm_os_window_close         0
enable_audio_bell               no
window_padding_width            0 6 0 6
placement_strategy              top-left
active_border_color             #ff00ff
allow_remote_control            yes

# splits
map alt+v launch --type=window --location=vsplit
map alt+h launch --type=window --location=hsplit

map alt+z toggle_layout stack

map alt+left  neighboring_window left
map alt+right neighboring_window right
map alt+up    neighboring_window up
map alt+down  neighboring_window down

map alt+shift+left move_window left
map alt+shift+right move_window right
map alt+shift+up move_window up
map alt+shift+down move_window down

# close pane
map alt+q close_window

# New tab
map alt+ctrl+w new_tab
map alt+ctrl+q close_tab

# Switch to tab 1–9
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

map ctrl+left_mouse_button open_url

map alt+ctrl+right resize_window narrower
map alt+ctrl+left resize_window wider

# Kanagawa Dragon-inspired theme for kitty
background            #151313
foreground            #d4d8d0

# Cursor
cursor                #d6c89a
cursor_text_color     #151313

# Selection
selection_background  #3a6380
selection_foreground  #f0ddb0

# Black
color0  #121111
color8  #b5b5aa

# Red
color1  #d27a73
color9  #f06d7f

# Green
color2  #95ad82
color10 #98c379

# Yellow
color3  #d1bc8f
color11 #f0c674

# Blue
color4  #91b2c4
color12 #86c1dc

# Magenta
color5  #ae9fc0
color13 #b29dd9

# Cyan
color6  #8fb8b2
color14 #7fc7bb

# White
color7  #ddd8bb
color15 #eef1e8
