# font handling
# Main font: pure JetBrains Mono (must be installed from JetBrains)
# Main font is the Nerd Font patched version
font_family      "JetBrainsMono Nerd Font"

# Bold/italic variants (optional, can stay auto)
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11


mouse_hide_wait                 2.0
cursor_shape                    beam
# cursor                          #fdfd96
cursor_beam_thickness           2
# url_color                       #fdfd96
url_style                       dotted
confirm_os_window_close         0
enable_audio_bell               no
placement_strategy              top-left
# active_border_color             #ff00ff
allow_remote_control            yes

# splits
map alt+w launch --type=window

map alt+z toggle_layout stack

map alt+left  neighboring_window left
map alt+right neighboring_window right
map alt+up    neighboring_window up
map alt+down  neighboring_window down

map alt+shift+left move_window left
map alt+shift+right move_window right
map alt+shift+up move_window up
map alt+shift+down move_window down

# close pane
map alt+q close_window

# New tab
map alt+ctrl+w new_tab
map alt+ctrl+q close_tab

# Switch to tab 1–9
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

map alt+ctrl+right resize_window narrower
map alt+ctrl+left resize_window wider

window_padding_height 6
window_padding_width  8

enabled_layouts tall:bias=50;full_size=1;mirrored=false


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
